name: Deploy to S3

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy-staging:
    name: Deployment to Amazon S3
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::381492218855:role/GithubActionRole
          aws-region: ap-southeast-1

      - name: Deploy S3
        run: aws s3 sync ./dist s3://alc-static-website-study-session --delete

      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id E3PV0EA2EX0H85  --paths "/*"
