name: React Test

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: React Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18.14.2

      - name: Install dependencies
        run: npm install

      - name: Lint Checker
        run: npm run lint

      - name: Build Checker
        run: npm run build
